##### Radar plot list of indicators

variables_list <- list(
  list(
    name = "Percentage of adults (16+) meeting the MVPA guideline",
    order = 1,
    dataset = "health_2019",
    dataset2 = "health_2015",
    raw_var = "adt10gpTW",           
    weight = "int16171819wt",  
    weight2 = "int12131415wt",
    strata = "Strata", 
    area = "HBCode",   
    to_binary = function(x) dplyr::case_when(x == 1 ~ 1, 
                                             x %in% 2:4 ~ 0, 
                                             x < 0 ~ NA_real_)
    ),
  list(
    name = "Percentage of children (5-15) meeting the MVPA guidelines",
    order = 2,
    dataset = "health5_15_2019",
    dataset2 = "health5_15_2015",
    raw_var = "c00sum7S",
    weight = "cint16171819wt",
    weight2 = "cint12131415wt",
    strata = "Strata",
    area = "HBCode",
    to_binary = function(x) dplyr::case_when(x == 1 ~ 1, 
                                             x %in% 2:3 ~ 0, 
                                             x < 0 ~ NA_real_)
    ), 
  list(
    name = "Percentage of adults (16+) meeting the muscle\nstrengthening guideline",
    order = 3,
    dataset = "health_2019",
    dataset2 = "health_2015",
    raw_var = "MusRec",           
    weight = "int16171819wt",
    weight2 = "int12131415wt",
    strata = "Strata",
    area = "HBCode",   
    to_binary = function(x) dplyr::case_when(x == 1 ~ 1, 
                                             x ==0 ~ 0, 
                                             x < 0 ~ NA_real_) 
  ),  
  list(
    name = "Percentage of adults (16+) participating in recreational walking",
    order = 4,
    dataset = "house_2019",
    dataset2 = "house_2015",
    raw_var = "sprt3aa",
    weight = "IND_WT",
    weight2 = "IND_WT",
    strata = "council",
    area = "council",
    to_binary = function(x) dplyr::case_when(x == 1 ~ 1, 
                                             x ==0 ~ 0, 
                                             is.na(x) ~ NA_real_)
  ),
  list(
    name = "Percentage of adults (16+) participating in sport",
    order = 5,
    dataset = "house_2019",
    dataset2 = "house_2015",
    raw_var = "anysportnowalk",
    weight = "IND_WT",
    weight2 = "IND_WT",
    strata = "council",
    area = "council",
    to_binary = function(x) dplyr::case_when(x == 1 ~ 1, 
                                             x == 0 ~ 0, 
                                             is.na(x) ~ NA_real_)
  ),  
  list(
    name = "Percentage of children (5-15) participating in sport",
    order = 6,
    dataset = "health5_15_2019",
    dataset2 = "health5_15_2015",
    raw_var = "spt1ch",
    weight = "cint16171819wt",
    weight2 = "cint12131415wt",
    strata = "Strata",
    area = "HBCode",
    to_binary = function(x) dplyr::case_when(x == 1 ~ 1, 
                                             x %in% 2 ~ 0, 
                                             x < 0 ~ NA_real_)
  ),
  list(
    name = "Percentage of adults (16+) usually\nwalking or cycling to work",
    order = 7,
    dataset = "house_2019",
    dataset2 = "house_2015",
    raw_var = "rd3",
    weight = "IND_WT",
    weight2 = "IND_WT",
    strata = "council",
    area = "council",
    to_binary = function(x) dplyr::case_when(x == 1 | x == 5 ~ 1, 
                                             x %in% 2:4 | x %in% 6:16 ~ 0, 
                                             is.na(x) ~ NA_real_)
  ),
  list(
    name = "Percentage of children (2-15) that use\nactive travel to get to school",
    order = 8,
    dataset = "house_2019",
    dataset2 = "house_2015",
    raw_var = "he10n",
    weight = "IND_WT",
    weight2 = "IND_WT",
    strata = "council",
    area = "council",
    to_binary = function(x) dplyr::case_when(x == 1 | x == 5 ~ 1, 
                                             x %in% 2:4 | x %in% 6:16 ~ 0, 
                                             is.na(x) ~ NA_real_)
  ),
  list(
    name = "Percentage of adults (16+) that visit\nthe outdoors at least once a week",
    order = 9,
    dataset = "house_2019",
    dataset2 = "house_2015",
    raw_var = "outdoor",
    weight = "IND_WT",
    weight2 = "IND_WT",
    strata = "council",
    area = "council",
    to_binary = function(x) dplyr::case_when(x %in% 1:4 ~ 1, 
                                             x %in% 5:8 ~ 0, 
                                             is.na(x) ~ NA_real_)
  ),
  list(
    name = "Percentage of adults (16+) that are satisfied\nwith their local sports and leisure facilities",
    order = 10,
    dataset = "house_2019",
    dataset2 = "house_2015",
    raw_var = "serv3a",
    weight = "IND_WT",
    weight2 = "IND_WT",
    strata = "council",
    area = "council",
    to_binary = function(x) dplyr::case_when(x %in% 1:2 ~ 1, 
                                             x %in% 3:6 ~ 0, 
                                             is.na(x) ~ NA_real_)
  ),
  list(
    name = "Percentage of adults (16+) that are satisfied\nwith their local parks and open spaces",
    order = 11,
    dataset = "house_2019",
    dataset2 = "house_2015",
    raw_var = "serv3e",
    weight = "IND_WT",
    weight2 = "IND_WT",
    strata = "council",
    area = "council",
    to_binary = function(x) dplyr::case_when(x %in% 1:2 ~ 1, 
                                             x %in% 3:6 ~ 0, 
                                             is.na(x) ~ NA_real_)
  )
)
  
  